/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author NICOLAS
 */
import Datos.Cadete;
import Datos.Cliente;
import Datos.Comida;
import Datos.Zona;
import Datos.detallePedido;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Datos.Pedido;
import Datos.Telefonos;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;

public class DatosPedidos extends javax.swing.JFrame {
    Telefonos tel= new Telefonos();
DefaultTableModel tablaPedido;
Pedido ped= new Pedido();
int idTel=0;
 int idComida=0;
 int idDetalle=0;
int idPedido=0;
 int idCliente=0;
 float importeTotal;
 int cantidad;
 float importeZon;
 
    /**
     * Creates new form pedidos
     */
     Calendar FechayHora= new Calendar() {

    @Override
    protected void computeTime() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected void computeFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void add(int i, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void roll(int i, boolean bln) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getMinimum(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getMaximum(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getGreatestMinimum(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getLeastMaximum(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
};
     Zona zona= new Zona();
     Comida comida = new Comida();
     Cliente cli = new Cliente();
     detallePedido detallePedido = new detallePedido();
     
    public DatosPedidos() {
        initComponents();
        this.setTitle("Pedidos a Realizar");
        String cabecera [] ={"Codigo","Descripcion","Cantidad","Precio Unitario","Precio Total"};
        tablaPedido= new DefaultTableModel ();
        jTable1.setModel(tablaPedido);
        tablaPedido.setColumnIdentifiers(cabecera);
        String fyh= fechayHora();
       jLabelFechaYHora.setText(fyh);
       setLocationRelativeTo(null);
       jLabelLugardeEnvio.setEnabled(false);
       jButtonNuevoCliente.setEnabled(false);
        cargarMenuItemsCadete();
    }
    public String fechayHora(){
        FechayHora= Calendar.getInstance();
        int año= FechayHora.get(Calendar.YEAR);
        int  mes = FechayHora.get(Calendar.MONTH);
        int dia = FechayHora.get(Calendar.DAY_OF_MONTH);
        int hora = FechayHora.get(Calendar.HOUR_OF_DAY);
        int minuto = FechayHora.get(Calendar.MINUTE);
        int segundo = FechayHora.get(Calendar.SECOND);
        
        String fechasyhoras= ""+dia+"/"+mes+"/"+año+" "+" "+"Hora Actual: "+hora+"-"+minuto+"-"+segundo+"";
        return fechasyhoras;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jPanelCliente = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonNuevoCliente = new javax.swing.JButton();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefonoClienteBuscado = new javax.swing.JTextField();
        jLabelApellidoyNombre = new javax.swing.JLabel();
        jTextFieldApellidoyNombre = new javax.swing.JTextField();
        jLabelDomicilio = new javax.swing.JLabel();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jLabelLugardeEnvio = new javax.swing.JLabel();
        jTextFieldLugardeEnvio = new javax.swing.JTextField();
        jLabelZona = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1ApellidoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1ImporteZOna = new javax.swing.JTextField();
        jTextField1Zona = new javax.swing.JTextField();
        jButtonAgregarTelefono = new javax.swing.JButton();
        jButton2LimpiarTelefono = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelComida = new javax.swing.JLabel();
        jComboBoxComida = new javax.swing.JComboBox();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelImportaTotal = new javax.swing.JLabel();
        jTextFieldImporteTotal = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jComboBox1SeleccionarCadete = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConfirmarPedido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelFechaYHora = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Cliente"));

        jLabel1.setText("Telefono:");

        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscar)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButtonNuevoCliente.setText("Nuevo Cliente");
        jButtonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoClienteActionPerformed(evt);
            }
        });

        jLabelTelefono.setText("Telefono:");

        jTextFieldTelefonoClienteBuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoClienteBuscadoActionPerformed(evt);
            }
        });

        jLabelApellidoyNombre.setText(" Nombre:");

        jTextFieldApellidoyNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoyNombreActionPerformed(evt);
            }
        });

        jLabelDomicilio.setText("Domicilio:");

        jLabelLugardeEnvio.setText("Lugar de Envio:");

        jTextFieldLugardeEnvio.setText("Belgrano 679");

        jLabelZona.setText("Zona:");

        jLabel2.setText("Apellido:");

        jTextField1ApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ApellidoClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Importe envio");

        jTextField1Zona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ZonaActionPerformed(evt);
            }
        });

        jButtonAgregarTelefono.setText("Agregar telefono");
        jButtonAgregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTelefonoActionPerformed(evt);
            }
        });

        jButton2LimpiarTelefono.setText("Borrar Telefono");
        jButton2LimpiarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2LimpiarTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButtonNuevoCliente)))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelZona)
                    .addComponent(jLabelTelefono)
                    .addComponent(jLabelApellidoyNombre)
                    .addComponent(jLabel2)
                    .addComponent(jLabelDomicilio)
                    .addComponent(jLabelLugardeEnvio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1Zona, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1ImporteZOna, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldLugardeEnvio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1ApellidoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldApellidoyNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelefonoClienteBuscado, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregarTelefono)
                            .addComponent(jButton2LimpiarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNuevoCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefonoClienteBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoyNombre)
                            .addComponent(jTextFieldApellidoyNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDomicilio)
                            .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLugardeEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLugardeEnvio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelZona)
                            .addComponent(jTextField1Zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1ImporteZOna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addComponent(jButtonAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2LimpiarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Pedido"));

        jLabelComida.setText("Comida:");

        jComboBoxComida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empanadas", "Bombas de queso", "Pizza", "Lomito Especial", "Matambre a la pizza" }));
        jComboBoxComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxComidaActionPerformed(evt);
            }
        });

        jLabelCantidad.setText("Cantidad:");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idComida", "Descripcion", "Cantidad", "Precio Unitario", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelImportaTotal.setText("Importe Total:");

        jTextFieldImporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImporteTotalActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jComboBox1SeleccionarCadete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione --" }));
        jComboBox1SeleccionarCadete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1SeleccionarCadeteActionPerformed(evt);
            }
        });

        jLabel5.setText("Elija su cadete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelImportaTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelComida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxComida, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgregar)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1SeleccionarCadete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComida)
                    .addComponent(jComboBoxComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jComboBox1SeleccionarCadete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelImportaTotal)
                        .addComponent(jTextFieldImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCancelar.setText("Atras");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonConfirmarPedido.setText("Confirma Pedido");
        jButtonConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarPedidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha Actual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonConfirmarPedido)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFechaYHora, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelFechaYHora, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonConfirmarPedido))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        GestionarPedidos volver = new GestionarPedidos();
        volver.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarPedidoActionPerformed
    try {
        
        ResultSet cliEncontrado= cli.BuscarXConId(idCliente);
         if (cliEncontrado.first()){
             ped.setIdCliente(cliEncontrado.getInt("idCliente"));
            ped.setLugarEnvio(jTextFieldLugardeEnvio.getText());
            if(cliEncontrado.getInt("zona")==1)
            {
                ped.setZona(1);
            }else
            {
                ped.setZona(0);
            }
            float total = importeTotal+ importeZon;
            ped.setEmitida(0);
            
            ped.setTotal(total);
            ped.setEstadoPedido(1);
            idPedido = ped.Insertar();
           // Cargar detalles 
             traerDatosTabla(idPedido);
          JOptionPane.showMessageDialog(this, "Pedido registrado", "Advertencia", JOptionPane.INFORMATION_MESSAGE);   
         }
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(DatosPedidos.class.getName()).log(Level.SEVERE, null, ex);
    }
              
    }//GEN-LAST:event_jButtonConfirmarPedidoActionPerformed
    public void traerDatosTabla(int idped) throws SQLException{          
           
        for (int i = 0; i < tablaPedido.getRowCount(); i++) {
               detallePedido.setIdPedido(idped);      
//               detallePedido.setIdComida(Integer.parseInt((String) tablaPedido.getValueAt(i, 0)));
//               detallePedido.setCantidad(Integer.parseInt((String)tablaPedido.getValueAt(i, 2)));
               String idCom = tablaPedido.getValueAt(i, 0).toString();
               detallePedido.setIdComida(Integer.parseInt(idCom));
               String Cantidad= tablaPedido.getValueAt(i, 2).toString();
               detallePedido.setCantidad(Integer.parseInt(Cantidad));
               detallePedido.setNumLinea(i);
               idDetalle= detallePedido.Insertar();
             }
            
        }

    public int getIdPedido() {
        return idPedido;
    }

    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }
    
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
            //agregar los clientes faltan!
            
             cantidad= Integer.parseInt(jTextFieldCantidad.getText());
             jTextFieldCantidad.setText("");  
             jTextFieldCantidad.requestFocus();
        try {
            
            ResultSet tipComida=comida.buscarX(jComboBoxComida.getSelectedItem().toString()); 
            idComida = tipComida.getInt("IdComida");
            float precioTotal= Float.parseFloat(tipComida.getString("precio"))*cantidad;
            //addRow es una funcion propia de la clase DefaultTableModel
            // en esta instruccion permite agregar filas a la tabla
            if(tipComida.first()){
                do{
              tablaPedido.addRow(new Object[]{tipComida.getString("idComida"),tipComida.getString("Descripcion"),cantidad,tipComida.getString("precio"),precioTotal});
                importeTotal= obtenerImporte();
                jTextFieldImporteTotal.setText(Float.toString(importeTotal));
                jTextFieldImporteTotal.setEditable(false);// esta funcion no le permite al usuario modificar elcampo jTextFile      
                }while(tipComida.next());  
                }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DatosPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
        Logger.getLogger(DatosPedidos.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed
    //ESte metodo,lo que hace es recorrer a la tabla Jtable para obtener el importeTotal   
    public float obtenerImporte(){
            float imporTotal=(float)0.0;
            for (int i = 0; i < tablaPedido.getRowCount(); i++) {
                imporTotal=imporTotal+(float)tablaPedido.getValueAt(i, 4);
        }
            return imporTotal;
        }
    private void cargarMenuItemsCadete(){
    
        jComboBox1SeleccionarCadete.removeAllItems();
        jComboBox1SeleccionarCadete.addItem("-- Seleccione --");
        try {
            Cadete cadete = new Cadete();
            ResultSet rs = cadete.traerCadetes();
            while(rs.next()){
                jComboBox1SeleccionarCadete.addItem(String.valueOf(rs.getString(3) + rs.getString(4)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatosPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jComboBoxComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxComidaActionPerformed
           
    }//GEN-LAST:event_jComboBoxComidaActionPerformed

    private void jTextFieldImporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImporteTotalActionPerformed
        
        
    }//GEN-LAST:event_jTextFieldImporteTotalActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int posicionBorrar= jTable1.getSelectedRow();
        tablaPedido.removeRow(posicionBorrar);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextField1ZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ZonaActionPerformed
        jTextFieldLugardeEnvio.setText("Belgrano 679");
    }//GEN-LAST:event_jTextField1ZonaActionPerformed

    private void jTextField1ApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ApellidoClienteActionPerformed

    private void jTextFieldApellidoyNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoyNombreActionPerformed

    }//GEN-LAST:event_jTextFieldApellidoyNombreActionPerformed

    private void jTextFieldTelefonoClienteBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoClienteBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoClienteBuscadoActionPerformed

    private void jButtonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoClienteActionPerformed
       Cliente cliente = new Cliente();
        Telefonos telefono = new Telefonos();
         
        jTextFieldTelefonoClienteBuscado.requestFocus();
        try{
        if(verificarCampos()){
            cliente.setTelefono(Integer.parseInt(jTextFieldTelefonoClienteBuscado.getText()));
            cliente.setApellido(jTextFieldApellidoyNombre.getText());
            cliente.setNombre(jTextField1ApellidoCliente.getText());
            cliente.setDomicilio(jTextFieldDomicilio.getText());
            jTextFieldLugardeEnvio.setText("Belgrano 679");
            cliente.setEstado(1);
            if("centrica".equals(jTextField1Zona.getText()))
            {
                cliente.setZona(1);
                
            }
            else 
                cliente.setZona(0);
            idCliente= cliente.Insertar();
            telefono.setCliente(idCliente);
            telefono.setTelefono(Integer.parseInt(jTextFieldTelefonoClienteBuscado.getText()));
            telefono.setEstado(1);
            telefono.Insertar();
            JOptionPane.showMessageDialog(this, "Se registro el Cliente ", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            
            limpiarVariables();
            jTextFieldTelefonoClienteBuscado.requestFocus();
        }
             //un cliente puede tener uno o varios numeros de celulares y un numero de telefono.           
           
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR!!", JOptionPane.ERROR_MESSAGE);
        }
       
        
    }//GEN-LAST:event_jButtonNuevoClienteActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        //Consultar por que el if del cliente.first no me funciona cuando ingreso un telefono que no existe
               jButtonNuevoCliente.setEnabled(false);
    try {
        // cambiar la forma de busqueda y hacerlo por la tabla de telefono
        if(verificarCampoTel() == true){   
           ResultSet telefonos= tel.BuscarX(Integer.parseInt(jTextFieldTelefono.getText()));
           if(telefonos.first()){
              do{
                  int idCli = telefonos.getInt("idCliente");
                  ResultSet clientes= cli.BuscarXConId(idCli);
                  if (clientes.first()){
         do{
             if(idCli== clientes.getInt("idCliente")) {
            jTextFieldTelefonoClienteBuscado.setText(Integer.toString(clientes.getInt("telefono")));
            jTextFieldTelefonoClienteBuscado.setEditable(false);
            jTextFieldApellidoyNombre.setText(clientes.getString("nombre"));
            jTextFieldApellidoyNombre.setEditable(false);
            jTextField1ApellidoCliente.setText(clientes.getString("apellido"));
            jTextField1ApellidoCliente.setEditable(false);
            jTextFieldDomicilio.setText(clientes.getString("domicilio"));
            jTextFieldDomicilio.setEditable(false);
            jTextFieldLugardeEnvio.setText("Av Belgrano 420");
            jTextFieldLugardeEnvio.setEditable(false);
            if(clientes.getInt("zona")==1)
            {
                jTextField1Zona.setText("centrica");
                jTextField1Zona.setEditable(false);
            }else {jTextField1Zona.setText("no centrica");
                    jTextField1Zona.setEditable(false);}
            ResultSet zon= zona.BuscarPorZona(jTextField1Zona.getText());
                if(zon.first()){
                   
                    if(jTextField1Zona.getText().equals(zon.getString("descripcion"))){
                        importeZon= zon.getFloat("precio");
                   jTextField1ImporteZOna.setText(Float.toString(zon.getFloat("precio")));
                   jTextField1ImporteZOna.setEditable(false);
                   
                    }else{
                        importeZon= zon.getFloat("precio");
                        jTextField1ImporteZOna.setText(Float.toString(zon.getFloat("precio")));
                   jTextField1ImporteZOna.setEditable(false);
                    }
                }
             }
             else{
                 JOptionPane.showMessageDialog(this, "No existe el cliente, por favor Registrelo ", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
             }
             idCliente= clientes.getInt("idCliente");
         }while (clientes.next());
          
        }
        else{
        
        jButtonNuevoCliente.setEnabled(true);
        jButtonBuscar.setEnabled(false);
        jTextFieldTelefono.setText("");
        jTextFieldTelefonoClienteBuscado.requestFocus();
        }
              }while(telefonos.next());
          }
           else{
            jButtonNuevoCliente.setEnabled(true);
            JOptionPane.showMessageDialog(this, "No existe el cliente, Incorporelo ", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
               
           }
 }else{
JOptionPane.showMessageDialog(this, "Ingrese un numero de telefono ", "Advertencia", JOptionPane.INFORMATION_MESSAGE); 
 }
                //Consultar por que no me funciona el mensaje de error o buscar !
              
        }
    catch (SQLException ex) {
        Logger.getLogger(DatosPedidos.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (ClassNotFoundException ex) {
        Logger.getLogger(DatosPedidos.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jButtonAgregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTelefonoActionPerformed

        Telefonos telefon= new Telefonos();

        try {
            ResultSet buscCli = cli.buscarPorTelefono(Integer.parseInt(jTextFieldTelefono.getText()));
            if(buscCli.first()){
                telefon.setCliente(buscCli.getInt("idCliente"));
                telefon.setTelefono(Integer.parseInt(jTextFieldTelefonoClienteBuscado.getText()));
                idTel = telefon.Insertar();
                JOptionPane.showMessageDialog(this, "Incorporado el nuevo Telefono del Cliente ", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "Error al agregar nuevo telefono  ", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DatosPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DatosPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonAgregarTelefonoActionPerformed

    private void jButton2LimpiarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2LimpiarTelefonoActionPerformed
        jTextFieldTelefonoClienteBuscado.setText("");
        jTextFieldTelefonoClienteBuscado.requestFocus();
        jTextFieldTelefonoClienteBuscado.setEditable(true);
    }//GEN-LAST:event_jButton2LimpiarTelefonoActionPerformed

    private void jComboBox1SeleccionarCadeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1SeleccionarCadeteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1SeleccionarCadeteActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2LimpiarTelefono;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregarTelefono;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmarPedido;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonNuevoCliente;
    private javax.swing.JComboBox jComboBox1SeleccionarCadete;
    private javax.swing.JComboBox jComboBoxComida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelApellidoyNombre;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelFechaYHora;
    private javax.swing.JLabel jLabelImportaTotal;
    private javax.swing.JLabel jLabelLugardeEnvio;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelZona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1ApellidoCliente;
    private javax.swing.JTextField jTextField1ImporteZOna;
    private javax.swing.JTextField jTextField1Zona;
    private javax.swing.JTextField jTextFieldApellidoyNombre;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldImporteTotal;
    private javax.swing.JTextField jTextFieldLugardeEnvio;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTelefonoClienteBuscado;
    // End of variables declaration//GEN-END:variables

    private void limpiarVariables() {
            jTextFieldTelefonoClienteBuscado.setText("");
            
            jTextFieldApellidoyNombre.setText("");
            
            jTextField1ApellidoCliente.setText("");
           
            jTextFieldDomicilio.setText("");
            
            jTextFieldLugardeEnvio.setText("");
            
            jTextField1Zona.setText("");
            
            jTextField1ImporteZOna.setText("");
            
    }
    public boolean verificarCampos(){
        
        if(!("").equals(jTextFieldTelefono))
        {
            if(!("").equals(jTextFieldApellidoyNombre)){
                if(!("").equals(jTextField1ApellidoCliente)){
                    if(!("").equals(jTextFieldDomicilio)){
                        if(!("").equals(jTextFieldLugardeEnvio)){
                         if(!("").equals(jTextField1Zona)){
                             if(!("").equals(jTextField1ImporteZOna))
                                 return true;
                                 } 
                         else return false;
                        }
                        else return false;
                    }
                    else return false;
                }
                else return false;
            }
        }else return false;
        return false;
    }

    public boolean verificarCampoTel(){     
     
        if(!"".equals(jTextFieldTelefono.getText())){   
        return true;
        }
        return false;
    }
        
    
    
}
