/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JFrame;

/**
 *
 * @author NICOLAS
 */
public class interfazUsuarioAdmi extends javax.swing.JFrame {

    /**
     * Creates new form interfazUsuarioAdmi
     */
    public interfazUsuarioAdmi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1AgregarEmpleado = new javax.swing.JButton();
        jTextField1Buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2BuscarEmpleado = new javax.swing.JButton();
        jButton2Modificar = new javax.swing.JButton();
        jButton3EliminarEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1DatosPersonalesEmp = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1AgregarEmpleado.setText("Agregar ");
        jButton1AgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AgregarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1AgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 95, -1, -1));

        jTextField1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 55, 103, -1));

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 55, 72, 20));

        jButton2BuscarEmpleado.setText("Buscar");
        getContentPane().add(jButton2BuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 54, 94, -1));

        jButton2Modificar.setText("Modiicar ");
        jButton2Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 95, -1, -1));

        jButton3EliminarEmpleado.setText("Eliminar ");
        jButton3EliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EliminarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3EliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 95, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 0));

        jTable1DatosPersonalesEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NombreUsuario", "Nombre", "Apellido", "tipoUsuario", "Contraseña", "Domicilio", "E-mail", "EstadoUsuario"
            }
        ));
        jScrollPane1.setViewportView(jTable1DatosPersonalesEmp);
        if (jTable1DatosPersonalesEmp.getColumnModel().getColumnCount() > 0) {
            jTable1DatosPersonalesEmp.getColumnModel().getColumn(0).setHeaderValue("NombreUsuario");
            jTable1DatosPersonalesEmp.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            jTable1DatosPersonalesEmp.getColumnModel().getColumn(2).setHeaderValue("Apellido");
            jTable1DatosPersonalesEmp.getColumnModel().getColumn(3).setHeaderValue("tipoUsuario");
            jTable1DatosPersonalesEmp.getColumnModel().getColumn(4).setHeaderValue("Contraseña");
            jTable1DatosPersonalesEmp.getColumnModel().getColumn(5).setHeaderValue("Domicilio");
            jTable1DatosPersonalesEmp.getColumnModel().getColumn(6).setHeaderValue("E-mail");
            jTable1DatosPersonalesEmp.getColumnModel().getColumn(7).setHeaderValue("EstadoUsuario");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 670, 150));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 107, 45));

        jLabel2.setText("VENTANA PRINCIPAL USUARIO ADMINISTRADOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 11, 257, -1));

        jLabel3Fondo.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jLabel3Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1AgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AgregarEmpleadoActionPerformed
    
        JFrame ventanaAgregarUsuario = new agregarEmpleado();
       ventanaAgregarUsuario.setVisible(true);
        setVisible(false);
        
        // TODO add your handling code here:
           // ocultarr la interaz general y luego visualizar la ventana agregar empleado
    }//GEN-LAST:event_jButton1AgregarEmpleadoActionPerformed

    private void jTextField1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ModificarActionPerformed
        // TRABAJAR CREAR UN OBJETO DE LA CLASE TABLA PARA MODIICAR LOS CAMPOS EXPUESTOS EN LA TABLA
        // 
    }//GEN-LAST:event_jButton2ModificarActionPerformed

    private void jButton3EliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3EliminarEmpleadoActionPerformed
         //TRABAJAR CREAR UN OBJETO DE LA CLASE TABLA PARA MODIICAR LOS CAMPOS EXPUESTOS EN LA TABLA
    }//GEN-LAST:event_jButton3EliminarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazUsuarioAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazUsuarioAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazUsuarioAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazUsuarioAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazUsuarioAdmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1AgregarEmpleado;
    private javax.swing.JButton jButton2BuscarEmpleado;
    private javax.swing.JButton jButton2Modificar;
    private javax.swing.JButton jButton3EliminarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3Fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1DatosPersonalesEmp;
    private javax.swing.JTextField jTextField1Buscar;
    // End of variables declaration//GEN-END:variables
}
